name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        # uses: aws-actions/configure-aws-credentials@v1
        # with:
        #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: ap-southeast-1
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::088044628795:user/github
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Images
        run: |
          docker build -t 088044628795.dkr.ecr.ap-southeast-1.amazonaws.com/s34-client:latest ./client
          docker build -t 088044628795.dkr.ecr.ap-southeast-1.amazonaws.com/s34-server:latest ./server
          docker push 088044628795.dkr.ecr.ap-southeast-1.amazonaws.com/s34-client:latest
          docker push 088044628795.dkr.ecr.ap-southeast-1.amazonaws.com/s34-server:latest

